In [1]:
from keras.layers import Input, Dense, Lambda, Layer, Conv2D, LeakyReLU, Reshape, Flatten, BatchNormalization
from keras.models import Model
from keras import backend as K
import numpy as np
import matplotlib.pyplot as plt
import pickle

Using TensorFlow backend.


In [2]:
f = open('data.pkl', 'rb')
data = pickle.load(f, encoding='bytes')

In [3]:
x_data, y_data = data

In [4]:
x_data.astype('float32')

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]], dtype=float32)

In [5]:
y_data.astype('float32')

array([ 0.,  1.,  0., ...,  0.,  1.,  0.], dtype=float32)

In [6]:
type(x_data)

numpy.ndarray

In [7]:
x_data.shape

(4824, 2238)

In [8]:
y_data = y_data.reshape(4824,1)

In [9]:
y_data.shape

(4824, 1)

In [10]:
y_data

array([[0],
       [1],
       [0],
       ..., 
       [0],
       [1],
       [0]])

In [11]:
x   = Input(shape=(2238,))
h1  = Dense(64*64*1, activation=LeakyReLU())(x)
re  = Reshape((64,64,1))(h1)
c1  = Conv2D(4,(2,2), padding='same', activation=LeakyReLU())(re)
c2  = Conv2D(16,(2,2), padding='same', activation=LeakyReLU())(c1)
c3  = Conv2D(32,(2,2), padding='same', activation=LeakyReLU())(c2)
c4  = Conv2D(64,(2,2), padding='same', activation=LeakyReLU())(c3)
fl  = Flatten()(c4)
h2  = Dense(1024, activation=LeakyReLU())(fl)
out = Dense(1, activation='softmax')(h2)

model = Model(x,out)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2238)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 4096)              9170944   
_________________________________________________________________
reshape_1 (Reshape)          (None, 64, 64, 1)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 64, 64, 4)         20        
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 64, 64, 16)        272       
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 64, 64, 32)        2080      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 64, 64, 64)        8256      
__________

In [12]:
model.compile(optimizer='Adam', loss= 'mse')

In [13]:
model.fit(x_data, y_data, batch_size=32, epochs=10, verbose=1)

Epoch 1/10


InternalError: Dst tensor is not initialized.
	 [[Node: Const_17 = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1024,1] values: [0][0][0]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'Const_17', defined at:
  File "/home/ishengfang/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ishengfang/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-6fd1c78188ed>", line 1, in <module>
    model.fit(x_data, y_data, batch_size=32, epochs=10, verbose=1)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1458, in fit
    self._make_train_function()
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1002, in _make_train_function
    self.total_loss)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/keras/optimizers.py", line 393, in get_updates
    ms = [K.zeros(shape) for shape in shapes]
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/keras/optimizers.py", line 393, in <listcomp>
    ms = [K.zeros(shape) for shape in shapes]
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 521, in zeros
    return variable(tf.constant_initializer(0., dtype=tf_dtype)(shape),
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 162, in __call__
    verify_shape=self.verify_shape)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 106, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ishengfang/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Dst tensor is not initialized.
	 [[Node: Const_17 = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1024,1] values: [0][0][0]...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]


In [ ]:
model.fit?