In [1]:
from keras.layers import Input, Dense, Lambda, Layer, Conv2D, LeakyReLU, Reshape, Flatten, BatchNormalization
from keras.models import Model
from keras import backend as K
import numpy as np
import matplotlib.pyplot as plt
import pickle

Using TensorFlow backend.


In [2]:
f = open('data.pkl', 'rb')
data = pickle.load(f, encoding='bytes')

In [3]:
x_data, y_data = data

In [4]:
x_data.astype('float32')

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]], dtype=float32)

In [5]:
y_data.astype('float32')

array([ 0.,  1.,  0., ...,  0.,  1.,  0.], dtype=float32)

In [6]:
type(x_data)

numpy.ndarray

In [7]:
x_data.shape

(4824, 2238)

In [8]:
y_data = y_data.reshape(4824,1)

In [9]:
y_data.shape

(4824, 1)

In [10]:
y_data

array([[0],
       [1],
       [0],
       ..., 
       [0],
       [1],
       [0]])

In [19]:
x   = Input(shape=(2238,))
h1  = Dense(64*64*1, activation=LeakyReLU())(x)
re  = Reshape((64,64,1))(h1)
c1  = Conv2D(2,(2,2), strides=2, padding='same', activation=LeakyReLU())(re)
c2  = Conv2D(4,(2,2), strides=2, padding='same', activation=LeakyReLU())(c1)
c3  = Conv2D(8,(2,2), strides=2, padding='same', activation=LeakyReLU())(c2)
c4  = Conv2D(16,(2,2), strides=2, padding='same', activation=LeakyReLU())(c3)
fl  = Flatten()(c4)
h2  = Dense(128, activation=LeakyReLU())(fl)
out = Dense(1, activation='softmax')(h2)

model = Model(x,out)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 2238)              0         
_________________________________________________________________
dense_10 (Dense)             (None, 4096)              9170944   
_________________________________________________________________
reshape_4 (Reshape)          (None, 64, 64, 1)         0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 32, 32, 2)         10        
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 16, 16, 4)         36        
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 8, 8, 8)           136       
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 4, 4, 16)          528       
__________

In [20]:
model.compile(optimizer='Adam', loss= 'mse', metrics=['accuracy'])

In [ ]:
model.fit(x_data, y_data, batch_size=32, epochs=10, verbose=1)

Epoch 1/10
4824/4824 [==============================] - 2s - loss: 0.4656 - acc: 0.5344      

In [ ]:
from keras.optimizers import *